export const join = (req, res) => res.send("Join")
export const edit = (req, res) => res.send("Edit")
export const remove = (req, res) => res.send("Remove")
export const login = (req, res) => res.send("Login")
export const logout = (req, res) => res.send("Logout")
